### ISSUE TITLE
nim-status needs an initialization mechanism that's stateful in memory

### ISSUE THREAD

**Issue by michaelsbradleyjr** [status-im/nim-status#117]
Because nim-status is a library it shouldn't make decisions about where to e.g. write its database file. There should be some initialization mechanism that instantiates some type/object that holds configuration information, e.g. the path to write its database file.

`nim-waku` has an explicit `init` and if you think about it, status-go must do something roughly equivalent behind the scenes.

See:

https://github.com/status-im/nim-waku/blob/master/waku/v2/node/wakunode2.nim#L103

https://github.com/status-im/nim-waku/blob/master/examples/v2/basic2.nim#L22-L27

I propose we follow nim-waku's lead and create an `init` proc that makes use of configuration data and returns an initialized object of type `Status`. The procs we've been adding in `lib/` could be refactored such that their first parameter is `T: type Status`.

In the shim we can encapsulate the procs in a way that using nim-status in place of status-go works as usual, i.e. the users don't have to explicitly call the lib proc named `init` or manually deal with the instantiated object of type `Status`.

Any thoughts on this @richard-ramos?

**Comment by richard-ramos** [comment]
Good idea, that would be helpful for scenarios like this https://github.com/status-im/nim-status/blob/01616a39379e8f2dc5cc22ee42c12952f7252cf3/nim_status/lib/accounts.nim#L15  to obtain the path of the DB file, as well as some default settings that could be overriden by the user i guess?
