### ISSUE TITLE
Add make target for upgdating migration .sql files

### ISSUE THREAD

**Issue by michaelsbradleyjr** [status-im/nim-status#126]
The idea is for the `make` target to copy the migration `.sql` files from `vendor/status-go` into `nim_status/lib/migrations`. It would be a target that we run *manually* whenever `vendor/status-go` is bumped.

Although migration `.sql` files can be added to status-go, I'm not sure if any are ever deleted. If we're not sure, then the safest thing for the target to do would be to first `rm -f nim_status/lib/migrations/*.sql` and then copy the files from status-go.

**Comment by emizzle** [comment]
Removing all sql files before copying makes sense as we’ll be switching commits of Status-go.

Maybe we could run this automatically as part of CI?
