### ISSUE TITLE
re-add profile tab & screens dealing with settings

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status#133]
re-add the profile tab, and re-add screens that deal mostly with settings that we have already implemented getSettings and updateSettings

* appearance screen
* sound screen
* language screen
* notifications screen
* browser settings screen
* advanced screen

**Comment by siphiuel** [comment]
We should invoke `getSettings` and `updateSettings` directly from nim-status.

However, we should support a fallback to status-go if necessary.
