### ISSUE TITLE
Attempt to instantiate `Status` (`nim-status`) object inside client task

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-status#178]
Likely to run in to problems with global variables inside `nim_status` code.

### Notes
1. Global variables will need to be hung off the global `Status` object.
2. Get rid of `nim-confutils` and instead use the loaded config values as params in the constructor.

**Comment by emizzle** [comment]
Successfully instantiated the Status object inside of the chat client: https://github.com/status-im/nim-status/commit/a773478c5a169b36985af9c675cbf94a70574bbb

**Comment by emizzle** [comment]
This was completed in the example chat app, which will be merged tomorrow!

**Comment by iurimatias** [comment]
closed by #173
