### ISSUE TITLE
Review capability of `nim-status` to generate accounts and fresh databases

### ISSUE THREAD

**Issue by emizzle** [status-im/nim-status#179]

**Comment by emizzle** [comment]
The majority of this has been done in https://github.com/status-im/nim-status/pull/174. Needs a review of its capabilities.

### Notes
1. Should create fresh `nim-sqlcipher` database if it does not exist.

**Comment by emizzle** [comment]
@michaelsbradleyjr and I were able to get this working in master after rebasing and were able to successfully create accounts!

**Comment by iurimatias** [comment]
done
