### ISSUE TITLE
Join Public Chat

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status#195]
`/join #topic`

already works with one topic (flag at compile time), we want to make this dynamic so we can join multiple topics using nim-waku
the terminal should show messages from whatever topics we are listening to

**Comment by michaelsbradleyjr** [comment]
> already works with one topic (flag at compile time), we want to make this dynamic

See my notes in #196. The topic can currently be set when starting the already compiled program:
```
build/chat --waku-content-topic:"/toy-chat/2/example/proto"
```

There ended being supporting changes for this issue (and #196) included in the finalized PR for the `/login` and `/logout` commands, which will be merged shortly.

I plan to start pushing commits into a draft PR for this issue tomorrow.
