### ISSUE TITLE
Generate new wallet account given private key

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status#197]
`/addaccount <privatekey>`

should add account to the logged in user, in a row in the database

**Comment by emizzle** [comment]
Review need for weakened db encryption. There may be no longer be a need, unless if nim-status is used in mobile in the future, at which point we might be able to add in with a compilation flag or similar.
https://github.com/status-im/nim-status/blob/master/nim_status/database.nim#L28-L31
```
result.exec("PRAGMA cipher_page_size = 1024")
  result.exec("PRAGMA kdf_iter = 3200")
  result.exec("PRAGMA cipher_hmac_algorithm = HMAC_SHA1")
  result.exec("PRAGMA cipher_kdf_algorithm = PBKDF2_HMAC_SHA1")
  result.exec("PRAGMA foreign_keys = ON")
  result.exec("PRAGMA journal_mode = WAL")
```
