### ISSUE TITLE
Implement core components and protocols

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-status#2]
Checklist for components to implement:

Rough overview: https://miro.com/app/board/o9J_kuuReug=/

Status Specs: https://github.com/status-im/specs

General direction is to enable someone to write an alternative client a modular fashion, e.g. https://github.com/status-im/status-console-client/ or https://github.com/status-im/nim-stratus 

- [ ] Status Message payloads (spec https://github.com/status-im/specs/blob/master/status-payloads-spec.md)
- [ ] Double Ratchet https://github.com/status-im/status-nim/issues/3
- [ ] MVDS https://github.com/status-im/status-nim/issues/4
- [x] Waku https://github.com/status-im/nimbus/tree/master/waku
- [x] devp2p https://github.com/status-im/nim-eth
- [x] libp2p https://github.com/status-im/nim-libp2p

**Comment by iurimatias** [comment]
closing this since this issue itself is basically an outdated backlog / issues already in github/zenhub and not a task per se (anymore)
