### ISSUE TITLE
The import command needs a guard re: creating a duplicate database

### ISSUE THREAD

**Issue by michaelsbradleyjr** [status-im/nim-status#203]
Currently, if you `/import` the same mnemonic and password without deleting the database it created on the first run, the program will crash.

There should be a check in the example client and/or a module in `nim_status` to avoid trying to overwrite a database that already exists.

**Comment by michaelsbradleyjr** [comment]
This seems to have been closed by #232. I tried `/import` of the same mnemonic twice and got an error:
```
Key file for address 0x... already exists
```

I'll wait for @emizzle to confirm and then we can close this issue.

**Comment by emizzle** [comment]
I think we have covered our bases on this issue, but let's keep it in mind in case we missed something.
