### ISSUE TITLE
Implement Double Ratchet

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-status#3]
Implement Double Ratchet as it is used in the Status protocol: https://github.com/status-im/specs/blob/master/status-secure-transport-spec.md

Go implementation: https://github.com/status-im/doubleratchet

**Comment by iurimatias** [comment]
@oskarth same here, is it feasible/better to compile the go doubleratchet client as library and use it in nim-status?

**Comment by oskarth** [comment]
That'd be a preferable route. This gets a bit gnarly, and touches on the whole "where do keys live" etc aspect of how exactly Go/Nim interop will work. How does it currently work with 1:1 chat in desktop?

In general, I'd try to use all the existing Go libs as black boxes, then isolate specific blockers for use (e.g. assumptions around key management etc).

**Comment by oskarth** [comment]
@iurimatias can we add a rationale when closing issue please? Otherwise it is hard for people to understand the context that lead to decision not to do it, and route used instead.

**Comment by iurimatias** [comment]
@oskarth we're just starting with a clean slate that's all, this issue will be re-added at some point
