### ISSUE TITLE
implement hashMessage in nim

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status#34]

**Comment by michaelsbradleyjr** [comment]
I forgot to move this *In Progress*. It's almost done, and includes a broader reshaping of the library for nim-oriented entrypoints and linked-as-C-library entrypoints. See: https://github.com/status-im/nim-status/compare/feat/nim-hashmessage

I've written nim tests and and now attempting to write tests for when it's consumed as a C library; in that respect, I'm also learning more re: `NimMain`, i.e. initializing Nim's gc in the context of a static library.
