### ISSUE TITLE
Implement MVDS

### ISSUE THREAD

**Issue by oskarth** [status-im/nim-status#4]
Implement MVDS, minimal viable data sync.

Spec: https://specs.vac.dev/specs/mvds.html

Go client: https://github.com/vacp2p/mvds

## Bonus

    proven interop with Go client
    test vectors to ensure correctness

**Comment by iurimatias** [comment]
@oskarth is it feasible/better to compile the go mvds client as library and use it in nim-status?

**Comment by oskarth** [comment]
Not 100% sure, would have to be investigated. I think it should be, interface-wise.

**Comment by oskarth** [comment]
Ditto https://github.com/status-im/nim-status/issues/3#issuecomment-870143006
