### ISSUE TITLE
integrate nim-sqlcipher into nim-status

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status#46]

**Comment by michaelsbradleyjr** [comment]
This was done a long time ago, and above this comment I'm writing I can see I changed its status to *Done* 20 days ago. I'm curious why it ended up back in new issues? (cc: @iurimatias).

**Comment by iurimatias** [comment]
@michaelsbradleyjr probably due to the change of board and the columns being different, in the stimbus board it's the same state https://app.zenhub.com/workspaces/stimbus-5efb239198af4e001e85a041/board?repos=194023285
