### ISSUE TITLE
generate a derived account

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status#70]
implement method that generates a derived account given a parent account. see spec at https://specs.status.im/spec/2

**Comment by richard-ramos** [comment]
Already implemented with the BIP32 work: https://github.com/status-im/nim-status/blob/4d33a969b29207033f4c264a0f689b9d4587400a/test/nim/bip32.nim#L10-L16
Use derivation path `m/44'/60'/0'/0/0` for wallets (this is for the first wallet),  and `m/43'/60'/1581'/0'/0` for the public key
