### ISSUE TITLE
Mailservers CRUD

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status#72]
- Create mailservers table in database
- method to save a mailserver
- method to delete a mailserver
- method to list mailservers

see https://github.com/status-im/status-go/blob/be683556ffb1ece9ff88ed8e2f12277dde75ee08/services/mailservers/database.go#L80

**Comment by michaelsbradleyjr** [comment]
This shouldn't be in new issues; since the PR is still open (like a lot of nim-status PRs) it should be in the Review/QA column or even the Done column becasue it's done for all intents and purposes.
