### ISSUE TITLE
epic - add nim tests for nim-status / shim

### ISSUE THREAD

**Issue by iurimatias** [status-im/nim-status#9]

**Comment by siphiuel** [comment]
We had a conversation with @Samyoul , and would like to ask for clarification: what exactly should these tests be, and where should they reside? Meaning, there are several options:
  - Unit/Integration tests within nim-status library.
  - End-to-end tests within each respective client project that uses the library, so this implies Nim tests inside nim-status-client and Clojure tests inside status-react.
  - A separate Nim project for testing the endpoints exported by nim-status.

**Comment by iurimatias** [comment]
in the context of this task, it should be it would be `Unit/Integration tests within nim-status library.` as in, one should be able to import the library file in the tests and run tests against the exposed API.

**Comment by iurimatias** [comment]
closing for now, given new direction
